[package]
name = "metricwhiz"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16" }
crossterm = "0.28.1"
ndarray = "0.16.0"
polars = { version = "0.41.3", features = ["csv", "lazy", "rows"] }
ratatui = "0.28.0"
strum = { version = "0.26.3", features = ["derive"] }
